// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5M8fMowpOuk4YBdnB4-3gjsoXnt_GvGc',
    appId: '1:582335850632:web:8fde6dc3ecb6891b95973d',
    messagingSenderId: '582335850632',
    projectId: 'zyraslot',
    authDomain: 'zyraslot.firebaseapp.com',
    storageBucket: 'zyraslot.firebasestorage.app',
    measurementId: 'G-H93JYWWEQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAigtBFNp3meYwWHvmH2w_DjtV43k8Jh5E',
    appId: '1:582335850632:android:d1e4885face2da2995973d',
    messagingSenderId: '582335850632',
    projectId: 'zyraslot',
    storageBucket: 'zyraslot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl1UwfJ3kcCTjBFYjKyfTfcruz-h4QVcs',
    appId: '1:582335850632:ios:1a85e182aec6a78195973d',
    messagingSenderId: '582335850632',
    projectId: 'zyraslot',
    storageBucket: 'zyraslot.firebasestorage.app',
    iosClientId: '582335850632-846c49200tlvdsjidslv3nps90hojs97.apps.googleusercontent.com',
    iosBundleId: 'com.example.zyraslot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5M8fMowpOuk4YBdnB4-3gjsoXnt_GvGc',
    appId: '1:582335850632:web:7d6f02ddc3500b4e95973d',
    messagingSenderId: '582335850632',
    projectId: 'zyraslot',
    authDomain: 'zyraslot.firebaseapp.com',
    storageBucket: 'zyraslot.firebasestorage.app',
    measurementId: 'G-TDDHJFQ7JW',
  );
}
